### PR TITLE
Fix location link on section email

### LINKED ISSUE #674: Fix location link on section email

### PR DESCRIPTION
**Pull request by nyet-ty**
Resolve #674 
## PR includes

-   [x] Bug Fix

### CODE REVIEW

File: src/modules/emailMethods.ts [hunk 1]
```diff
@@ -134,9 +134,7 @@ export const assignSectionEmail = async (data: AssignSectionEmailData) => {
         start: exception.date,
         description: data.description || exception.eventDetails.description,
         duration: exception.eventDetails.duration,
-        summary: data.sectionTypeTitle
-            ? `${data.sectionTypeTitle} ${tr('with')} ${data.candidateName}`
-            : `${tr('Interview with')} ${data.candidateName}`,
+        summary: `${data.sectionTypeTitle} ${tr('with')} ${data.candidateName}`,
```
Comment (tsumo) [inline src/modules/emailMethods.ts:137]: update i18n

Comment (9teen90nine) [inline src/modules/emailMethods.ts:137]: Why did you change it?

**Review by tsumo — CHANGES_REQUESTED** [review]

File: src/modules/emailMethods.ts (hunk 1 above)
Comment (nyet-ty) [reply src/modules/emailMethods.ts:137]: sectionTypeTitle is obligatory field, so this ternar doesn't make sense

**Review by 9teen90nine — APPROVED** [review]

**Review by tsumo — APPROVED** [review]
