### PR TITLE
Fix: candidate creation

### LINKED ISSUE #40: Fix: candidate creation

### PR DESCRIPTION
**Pull request by nyet-ty**
Resolve #40

### CODE REVIEW

File: src/components/candidates/AddOrUpdateCandidate.tsx [hunk 1]
```diff
@@ -112,7 +122,7 @@ export const AddOrUpdateCandidate: VFC<AddOrUpdateCandidateProps> = (props) => {
             onSubmitButton={handleSubmit(onSubmit)}
             submitButtonDisabled={isSubmitting}
         >
-            <FormInput label="Full name" helperText={String(errors.name?.message)} forwardRef={refName} {...restName} />
+            <FormInput label={tr("Full name")} helperText={errors.name?.message} forwardRef={refName} {...restName} />
```
Comment (awinogradov) [inline src/components/candidates/AddOrUpdateCandidate.tsx:125]: double quotes?

Comment (nyet-ty) [reply src/components/candidates/AddOrUpdateCandidate.tsx:125]: my bad
