### PR TITLE
Section by calendar exception bug(slot double)

### LINKED ISSUE #623: Section by calendar exception bug(slot double)
If you assign section via calendar, but then cancel it - calendar slot will be free(exception from event series, but without section on it). If you you assign section on same slot it may be doubled: instead of using existed exception from series will be added new exception. In one scenario it can happen on hire calendar(if exception just created and calendar on front still does't know about it), on another - event will be doubled only on users Ical.

Need to add check in sectionMethods.ts in section create, if event series really does not have exception on chosen date

### PR DESCRIPTION
**Pull request by nyet-ty**
Resolve #623 

## PR includes

-   [x] Bug Fix

### CODE REVIEW

**Review by 9teen90nine — APPROVED** [review]

File: src/modules/sectionMethods.ts [hunk 1]
```diff
@@ -28,7 +28,9 @@ async function getCalendarSlotData(
     }
 
     const { eventId, exceptionId, originalDate } = params;
-    await calendarMethods.isEventExceptionAlreadyLinked(originalDate, eventId);
+    const existiongExeptionId = await calendarMethods.isEventExceptionAlreadyExist(originalDate, eventId);
```
Comment (tsumo) [inline src/modules/sectionMethods.ts:31]: existiOng
ExCeptionId

**Review by tsumo — CHANGES_REQUESTED** [review]

**Review by Katrin-kudryash — APPROVED** [review]

**Review by tsumo — APPROVED** [review]
